name: Deploy tutorials
on:
  push:
    branches:
      - main

jobs:
  generate-job-strategy-matrix:
    runs-on: ubuntu-latest
    outputs:
      job-strategy-matrix: ${{ steps.generate.outputs.job-strategy-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      # - name: Install python
      #   uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.10'
      - id: generate
        name: generate
        run: |
          # FILES=$(git diff --name-only HEAD HEAD~1 | grep jmd)
          # FILES=$(git diff --name-only HEAD HEAD~1)
          MATRIX=$((
            echo '{ "files": ['
            git diff --name-only HEAD HEAD~1 | sed -r 's/(.*)/\"\1\"/g' | sed '$!s/$/,/'
            echo ']}'
          ) | jq -c .)
          echo $MATRIX
          echo $MATRIX | jq .
          echo "::set-output name=job-strategy-matrix::$MATRIX"


  tutorial:
    needs: generate-job-strategy-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-job-strategy-matrix.outputs.job-strategy-matrix) }}
    steps:
      - run: echo "Job >>${{ matrix.files }}<<"
