name: Deploy all tutorials
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate-job-strategy-matrix:
    runs-on: ubuntu-latest
    outputs:
      job-strategy-matrix: ${{ steps.generate.outputs.job-strategy-matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 5
      - id: generate
        name: generate
        run: |
          MATRIX=$((
            echo '{ "tutorial": ['
            find . -name "*.jmd" | sed -r 's/.\/(.*)/\"\1\"/g' | sed '$!s/$/,/'
            echo ']}'
          ) | jq -c .)
          echo $MATRIX
          echo $MATRIX | jq .
          echo "::set-output name=job-strategy-matrix::$MATRIX"


  tutorial:
    needs: generate-job-strategy-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.generate-job-strategy-matrix.outputs.job-strategy-matrix) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1
      - run: |
          pwd
          ls
          bash .github/workflows/build_tutorial.sh ${{ matrix.tutorial }}
